# Generated by Django 5.2.7 on 2025-10-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profils',
            name='nom',
        ),
        migrations.AddField(
            model_name='profils',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
